;=====================================================================
; Font definitions using 4x8 font
;---------------------------------------------------------------------
; Copyright (C) 2021 Lawrence Woodman <lwoodman@vlifesystems.com>
; Licensed under an MIT licence.  Please see LICENCE.md for details.
;=====================================================================


fontDef
chA       .byt  %00000000
          .byt  %01111110
          .byt  %00001001
          .byt  %01111110

chB       .byt  %00000000
          .byt  %01111111
          .byt  %01001001
          .byt  %00110110
